apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakV5TVRjeApOVE13TURkYUZ3MDBNakV5TVRjeE5UTXdNRGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZlR1eTNKak52VzdvbmhnS3J2K0ZyQXBKTzFFN1c1VmozQUNtMWtoL3MxZ3Uwa05KbApEbmF5ODJ4ckZGWHMxMnJDa3JiRFAxenhYMitjcGNuUlVYS0h1Qm5DRHJMcnVVQ2JvMUQzWDlCYXdNanAxQm5tCkx6aG1EOGNkZm5rQmxQNmJBeHBLNGk5alBSMkNUSTdyektWNjF2VitrNDMzOGlQMW4xb2JCeUFMbTM2VHIvT1YKbjZRSi9FdHNNSksrejRFaHBON21Ed1hCeEZrN3p0WUN1VVcvODhWQ3RBcmRINWJVQnhvK1JqWTl1UGRvNlNhVApBZHQvZjVHSmEwVHRKbGpuTzNKMVdXUXdNZXAzQkdZQkhyVlRQcDNNODkwV1dHNTF4RUxmNGxyYVlaTjVBdG4zClFLVDZyaWhUR0d4ODF3R0xFUU9GTjVOZXVqMDRtd0VnNGRoaEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFtVEk1YkhZLzh0bVBrMXFpdApXZzZBRlNkL3N6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFEL3UvU29jR2dOWk03TDVKdkVKU3JVWEFPZ05ICmg3anFsUFdDWXorbklGMk93WHkzZWRjTlVoTFRHTUpwTGZlWlM1eU5uUDFrT21FZ0JrdFJiYS9LaFFSV1dYRjUKQWc1SXR6eUdMWnE2M2oxZ2oxdlB2TVpJd2dUcEJ5T0Nsb0pGNWFhTXE2MDBmbHBmb0RQUnd5Z1R1UU1YbmV3aAo4UUNZSFcvdjhnSSthcnpoZC93TWhvUDNMMCsrN1EwcWlmYzFXazhsbjRjQWtpVTVTMXdFdjRMRXVZVUJBenY4CnIwSVRLa0pnSXA1QVF4U3FudkRVS3BjbEYxNi9VWVlwWkFyeFNBa1dzS1VVVnNnV1Z3bXZVZzd3VDJvMHZyeEgKSkVpdGlIVFpYWGQxT055N2F6QTFYek5hZmxBQ0FqYmVxc1V2TFlPSjFMa245aldHVm1IMUJlN2VIdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://0692127a-af18-4f3d-9651-20c482280120.k8s.ondigitalocean.com
  name: do-sfo3-django-k8s
contexts:
- context:
    cluster: do-sfo3-django-k8s
    user: do-sfo3-django-k8s-admin
  name: do-sfo3-django-k8s
current-context: do-sfo3-django-k8s
kind: Config
preferences: {}
users:
- name: do-sfo3-django-k8s-admin
  user:
    token: dop_v1_0deb47c03d0646f64c3306d8832e260d92b496d9704a0ec9c64dadec1554546d
